global:
  scrape_interval: 5s  # How often to collect metrics

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Target your metrics endpoint
